app = "sober-styx"
primary_region = "ewr"

[vm]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048

[[services]]
  protocol = "tcp"
  internal_port = 2222
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 2222

[mounts]
  source = "styx_data"
  destination = "/data"
