repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        name: Secret Scanning
        description: Detect hardcoded secrets using Gitleaks
        entry: gitleaks protect --verbose --redact --staged
        language: system

  - repo: local
    hooks:
      - id: nixfmt
        name: nixfmt
        description: Format Nix files
        entry: nixfmt
        language: system
        files: \.nix$
        
      - id: deadnix
        name: deadnix
        description: Find dead Nix code
        entry: deadnix --edit
        language: system
        files: \.nix$

      - id: statix
        name: statix
        description: Lints and suggestions for Nix code
        entry: sh -c 'for f in "$@"; do statix fix "$f"; done' --
        language: system
        files: \.nix$
