keys:
  - &michael ***REDACTED***
  - &otus age18dss0maw2stj9ljr6dk3k32lsvl86nnvrr808j5mx7wep44u5etqhyxrgc
  - &ninox age1xx3mduh8hz3327mclqgyyxr5fm2xvuper73gfde98cytx47d04qsv9dj5l

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *michael
          - *otus
          - *ninox
