
[Interface]
PrivateKey = REDACTED_WG_KEY
Address = fdaa:3:7a15:a7b:8cfe:a5b7:ab47:4102/120
DNS = fdaa:3:7a15::3

[Peer]
PublicKey = q+cTUCrE9NekeuZEF/gCYxr2wNBjvYgGoqYwV1logEI=
AllowedIPs = fdaa:3:7a15::/48
Endpoint = iad2.gateway.6pn.dev:51820
PersistentKeepalive = 15

