app = "sober-bubo"
primary_region = "ewr"

[mounts]
  source = "bubo_data"
  destination = "/data"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 2222
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 2222


