app = "sober-athene"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "nix_data"
  destination = "/data"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[services]]
  protocol = "tcp"
  internal_port = 6667
  [[services.ports]]
    port = 6667

[[services]]
  protocol = "tcp"
  internal_port = 6167
  [[services.ports]]
    port = 6167

[[services]]
  protocol = "tcp"
  internal_port = 8081
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
