app = "sober-athene"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "nix_data"
  destination = "/var/lib/soju"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[services]]
  protocol = "tcp"
  internal_port = 6697
  [[services.ports]]
    port = 6697

[[services]]
  protocol = "tcp"
  internal_port = 8080
  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

