app = "sober-glaucidium"
primary_region = "fra"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[services]]
  protocol = "udp"
  internal_port = 51820
  [[services.ports]]
    port = 51820
