#!/usr/bin/env bash
set -e

echo "🚀 Starting Fedora-based Nix Builder..."

# 1. Setup Persistent Storage (OverlayFS for Nix)
# We use the /nix from the image as the base, and store changes in the volume.
mkdir -p /var/lib/nix_persist/nix_upper /var/lib/nix_persist/nix_work
# We must move the existing /nix content to a temporary location if the volume is empty,
# or just overlay directly if we want to keep the image's nix as the lower layer.
echo "📦 Mounting persistent Nix store..."
mount -t overlay overlay -o lowerdir=/nix,upperdir=/var/lib/nix_persist/nix_upper,workdir=/var/lib/nix_persist/nix_work /nix

# 2. Setup Authorized Keys for Root
mkdir -p /root/.ssh
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAPGyqlLfLc3PTAQ00M2fg4kaEnoOkmMfECNGOQo/2FI" > /root/.ssh/authorized_keys
chmod 700 /root/.ssh
chmod 600 /root/.ssh/authorized_keys

# 2. Persistent SSH Host Keys
# Fly microVMs lose files in /etc on restart. We persist keys to our volume.
mkdir -p /var/lib/nix_persist/ssh
if [[ "$(ls /var/lib/nix_persist/ssh/*_key 2>/dev/null)" = "" ]]; then
    echo "🔑 Generating new host keys on persistent volume..."
    ssh-keygen -A
    cp /etc/ssh/ssh_host_*_key* /var/lib/nix_persist/ssh/
else
    echo "🔑 Restoring host keys from persistent volume..."
    cp -f /var/lib/nix_persist/ssh/ssh_host_*_key* /etc/ssh/
    chmod 600 /etc/ssh/ssh_host_*_key
fi

# 3. Ensure Nix environment is available
if [ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
fi

# 4. Start Nix Daemon in background
echo "❄️ Starting Nix Daemon..."

# Configure custom nix settings
mkdir -p /etc/nix
cat <<EOF > /etc/nix/nix.custom.conf
builders-use-substitutes = true
trusted-substituters = https://cache.nixos.org https://cache.flakehub.com
extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.flakehub.com-3:hJuILl5sVK4iKm86JzgdXW12Y2Hwd5G07qKtHTOcDCM= cache.flakehub.com-4:Asi8qIv291s0aYLyH6IOnr5Kf6+OF14WVjkE6t3xMio= cache.flakehub.com-5:zB96CRlL7tiPtzA9/WKyPkp3A2vqxqgdgyTVNGShPDU= cache.flakehub.com-6:W4EGFwAGgBj3he7c5fNh9NkOXw0PUVaxygCVKeuvaqU= cache.flakehub.com-7:mvxJ2DZVHn/kRxlIaxYNMuDG1OvMckZu32um1TadOR8= cache.flakehub.com-8:moO+OVS0mnTjBTcOUh2kYLQEd59ExzyoW1QgQ8XAARQ= cache.flakehub.com-9:wChaSeTI6TeCuV/Sg2513ZIM9i0qJaYsF+lZCXg0J6o= cache.flakehub.com-10:2GqeNlIp6AKp4EF2MVbE1kBOp9iBSyo0UPR9KoR0o1Y=
EOF

/nix/var/nix/profiles/default/bin/nix-daemon &

# Wait for daemon
sleep 2

# Cleanup old generations to free space
echo "🧹 Cleaning up Nix store to free space..."
/nix/var/nix/profiles/default/bin/nix-collect-garbage -d || true

# 5. Activate Home Manager configuration
echo "🏠 Activating Home Manager configuration..."
export USER=root
export HOME=/root
export LOGNAME=root
export NIXPKGS_ALLOW_UNFREE=1
/nix/var/nix/profiles/default/bin/home-manager switch --flake /repo#server --impure

# 6. Start processes
echo "📡 Starting SSHD on port 2222 (mapped to 22)..."
/usr/sbin/sshd -e &

echo "💬 Starting Soju Bouncer..."
# We use the config generated by Home Manager
exec /nix/var/nix/profiles/default/bin/soju -config /root/.config/soju/config
