app = "sober-services"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "nix_data"
  destination = "/var/lib/nix_persist"

[vm]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 4096

[[services]]
  protocol = "tcp"
  internal_port = 2222
  [[services.ports]]
    port = 22
