[Interface]
Address = 10.13.13.1/24
ListenPort = 51820
PrivateKey = 0DGVDVBobtwR3yoX290O0naF1Wswmi2pbwJmnSV9L2w=
# NAT/Masquerading
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
# Client OTUS
PublicKey = mLpRrytjze69fuDpFkxwmYmB5ZBHyJKizfos9jyKWAM=
AllowedIPs = 10.13.13.2/32
