{ pkgs, ... }:

let
  brandName = "SOBER";
  mascot = "Owl";

  projectInfo = {
    inherit brandName mascot;
    year = "2026";
  };
in
{
  home.file."sober-mmanifesto.txt".text = ''
    --- SYSTEM IDENTITY ---
    Brand: ${projectInfo.brandName}
    Mascot: ${projectInfo.mascot}
    Year: ${projectInfo.year}

    Status: This system is being build from scratch
    Generated by Nix via (via ${pkgs.coreutils}/bin/whoami )
  '';
}
