listen irc+insecure://0.0.0.0:6697
listen unix+admin:///var/lib/soju/admin.sock
listen http+insecure://0.0.0.0:8080
http-ingress https://sober-athene.fly.dev
file-upload fs /var/lib/soju/uploads
db sqlite3 /var/lib/soju/soju.db
