
[Interface]
PrivateKey = YGy93Dbs9jetyXsp0Xi9fZqkeV9yvPKRwyxqaxOiDh0=
Address = fdaa:3:7a15:a7b:8cfe:5277:7317:d402/120
DNS = fdaa:3:7a15::3

[Peer]
PublicKey = q+cTUCrE9NekeuZEF/gCYxr2wNBjvYgGoqYwV1logEI=
AllowedIPs = fdaa:3:7a15::/48
Endpoint = iad2.gateway.6pn.dev:51820
PersistentKeepalive = 15

